.TH "dimensional_variables" 3 "Thu Nov 16 2017" "Version 1" "Hard_Spheere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dimensional_variables \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, parameter \fBdistu\fP =1\&.d0"
.br
.ti -1c
.RI "real *8, parameter \fBd0u\fP =1\&.d0"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "real * 8, parameter dimensional_variables::d0u =1\&.d0"

.PP
Definition at line 13 of file variables_modules\&.f90\&.
.SS "real * 8, parameter dimensional_variables::distu =1\&.d0"

.PP
Definition at line 12 of file variables_modules\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hard_Spheere from the source code\&.
