.TH "headers/file_manage.hpp" 3 "Thu Nov 16 2017" "Version 1" "Hard_Spheere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers/file_manage.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <limits>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFile_Manage\fP"
.br
.RI "\fIClase para el manejo de archivos\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hard_Spheere from the source code\&.
