.TH "File_Manage" 3 "Thu Nov 16 2017" "Version 1" "Hard_Spheere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
File_Manage \- Clase para el manejo de archivos\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <file_manage\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFile_Manage\fP ()"
.br
.ti -1c
.RI "\fBFile_Manage\fP (const std::string &str, bool truncate)"
.br
.ti -1c
.RI "void \fBsave_sk\fP (double *sk, double *k, int Kpoints, int species)"
.br
.ti -1c
.RI "bool \fBread_Sk\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBfile_name\fP"
.br
.ti -1c
.RI "bool \fBtruncate_file\fP"
.br
.ti -1c
.RI "std::ofstream \fBoutfile\fP"
.br
.ti -1c
.RI "std::ifstream \fBinfile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Clase para el manejo de archivos\&. 

Esta clase permite la manipulacion de archivos de tal manera que se pueden realizar las acciones basicas como son, abrir guardar y modificar un archivo\&. Estos archivos basicamente contienen los datos calulados del factor de estructura\&.
.PP
\fBAuthor:\fP
.RS 4
: delcranck 
.RE
.PP
\fBDate:\fP
.RS 4
: 28/08/2017 
.RE
.PP

.PP
Definition at line 15 of file file_manage\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "File_Manage::File_Manage ()"
Constructor default 
.PP
Definition at line 4 of file file_manage\&.cpp\&.
.SS "File_Manage::File_Manage (const std::string & str, bool truncate)"
Constructor que puede especificar el archivo y si desea truncarse 
.PP
Definition at line 7 of file file_manage\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool File_Manage::read_Sk ()"
Lee el sk 
.PP
Definition at line 38 of file file_manage\&.cpp\&.
.SS "void File_Manage::save_sk (double * sk, double * k, int Kpoints, int species)"
Guarda el sk 
.PP
Definition at line 15 of file file_manage\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string File_Manage::file_name\fC [protected]\fP"
Nombre del archivo, dicho nombre contiene la ruta del mismo 
.PP
Definition at line 34 of file file_manage\&.hpp\&.
.SS "std :: ifstream File_Manage::infile\fC [protected]\fP"
Permite realizar operaciones de lectura 
.PP
Definition at line 37 of file file_manage\&.hpp\&.
.SS "std :: ofstream File_Manage::outfile\fC [protected]\fP"
Permite realizar operaciones de escritura 
.PP
Definition at line 36 of file file_manage\&.hpp\&.
.SS "bool File_Manage::truncate_file\fC [protected]\fP"
Bandera que determina si el archivo debe de ser truncado o no 
.PP
Definition at line 35 of file file_manage\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Hard_Spheere from the source code\&.
