.TH "Hard_Sphere_Mono" 3 "Thu Nov 16 2017" "Version 1" "Hard_Spheere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hard_Sphere_Mono \- realiza todas las operaciones para el calculo de Sk de esfera dura  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hard_sphere_mono\&.hpp>\fP
.PP
Inherits \fBStatic_Variables\fP, and \fBSys_Variables\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHard_Sphere_Mono\fP ()"
.br
.ti -1c
.RI "\fBHard_Sphere_Mono\fP (double _vol_fraction)"
.br
.ti -1c
.RI "void \fBcalc_static_K\fP ()"
.br
.ti -1c
.RI "void \fBcalc_Sk_hs_py_mono\fP (bool VW_op)"
.br
.ti -1c
.RI "double * \fBget_K\fP ()"
.br
.ti -1c
.RI "int \fBget_KPoints\fP ()"
.br
.ti -1c
.RI "int \fBget_Species\fP ()"
.br
.ti -1c
.RI "double * \fBget_sk\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
realiza todas las operaciones para el calculo de Sk de esfera dura 


.PP
Definition at line 10 of file hard_sphere_mono\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Hard_Sphere_Mono::Hard_Sphere_Mono ()"

.PP
Definition at line 4 of file hard_sphere_mono\&.cpp\&.
.SS "Hard_Sphere_Mono::Hard_Sphere_Mono (double _vol_fraction)"

.PP
Definition at line 12 of file hard_sphere_mono\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Hard_Sphere_Mono::calc_Sk_hs_py_mono (bool VW_op)"

.PP
Definition at line 35 of file hard_sphere_mono\&.cpp\&.
.SS "void Hard_Sphere_Mono::calc_static_K ()"

.PP
Definition at line 26 of file hard_sphere_mono\&.cpp\&.
.SS "double * Hard_Sphere_Mono::get_K ()"

.PP
Definition at line 96 of file hard_sphere_mono\&.cpp\&.
.SS "int Hard_Sphere_Mono::get_KPoints ()"

.PP
Definition at line 106 of file hard_sphere_mono\&.cpp\&.
.SS "double * Hard_Sphere_Mono::get_sk ()"

.PP
Definition at line 101 of file hard_sphere_mono\&.cpp\&.
.SS "int Hard_Sphere_Mono::get_Species ()"

.PP
Definition at line 111 of file hard_sphere_mono\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Hard_Spheere from the source code\&.
