.TH "nescgle_variables" 3 "Thu Nov 16 2017" "Version 1" "Hard_Spheere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nescgle_variables \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBnescgle_static_variables_mem_alloc\fP (Ialloc_k, Ialloc_s)"
.br
.ti -1c
.RI "subroutine \fBnescgle_static_variables_mem_dealloc\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, parameter \fBdu\fP =1\&.d\-2"
.br
.ti -1c
.RI "real *8, dimension(:,:,:), allocatable \fBsk0\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:,:), allocatable \fBskf\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine nescgle_variables::nescgle_static_variables_mem_alloc (integer, intent(in) Ialloc_k, integer, intent(in) Ialloc_s)"

.PP
Definition at line 230 of file variables_modules\&.f90\&.
.SS "subroutine nescgle_variables::nescgle_static_variables_mem_dealloc ()"

.PP
Definition at line 236 of file variables_modules\&.f90\&.
.SH "Variable Documentation"
.PP 
.SS "real * 8, parameter nescgle_variables::du =1\&.d\-2"

.PP
Definition at line 225 of file variables_modules\&.f90\&.
.SS "real * 8, dimension (:,:,:), allocatable nescgle_variables::sk0"

.PP
Definition at line 226 of file variables_modules\&.f90\&.
.SS "real * 8, dimension (:,:,:), allocatable nescgle_variables::skf"

.PP
Definition at line 226 of file variables_modules\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hard_Spheere from the source code\&.
