.TH "parameter_variables" 3 "Thu Nov 16 2017" "Version 1" "Hard_Spheere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parameter_variables \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, parameter \fBpi\fP =4\&.d0*DATAN(1\&.d0)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "real * 8, parameter parameter_variables::pi =4\&.d0*DATAN(1\&.d0)"

.PP
Definition at line 5 of file variables_modules\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hard_Spheere from the source code\&.
