.TH "headers/static_variables.hpp" 3 "Thu Nov 16 2017" "Version 1" "Hard_Spheere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers/static_variables.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStatic_Variables\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hard_Spheere from the source code\&.
