.TH "static_variables" 3 "Thu Nov 16 2017" "Version 1" "Hard_Spheere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
static_variables \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBstatic_variables_mem_alloc\fP (Ialloc_k, Ialloc_s)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer \fBkpoints\fP"
.br
.ti -1c
.RI "real *8 \fBdk\fP"
.br
.ti -1c
.RI "real *8, dimension(:), allocatable \fBk\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:,:), allocatable \fBsk\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:,:), allocatable \fBski\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:,:), allocatable \fBck\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:,:), allocatable \fBhk\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine static_variables::static_variables_mem_alloc (integer, intent(in) Ialloc_k, integer, intent(in) Ialloc_s)"

.PP
Definition at line 132 of file variables_modules\&.f90\&.
.SH "Variable Documentation"
.PP 
.SS "real * 8, dimension (:,:,:), allocatable static_variables::ck"

.PP
Definition at line 128 of file variables_modules\&.f90\&.
.SS "real * 8 static_variables::dk"

.PP
Definition at line 126 of file variables_modules\&.f90\&.
.SS "real * 8, dimension (:,:,:), allocatable static_variables::hk"

.PP
Definition at line 128 of file variables_modules\&.f90\&.
.SS "real * 8, dimension(:), allocatable static_variables::k"

.PP
Definition at line 127 of file variables_modules\&.f90\&.
.SS "integer static_variables::kpoints"

.PP
Definition at line 125 of file variables_modules\&.f90\&.
.SS "real * 8, dimension (:,:,:), allocatable static_variables::sk"

.PP
Definition at line 128 of file variables_modules\&.f90\&.
.SS "real * 8, dimension (:,:,:), allocatable static_variables::ski"

.PP
Definition at line 128 of file variables_modules\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hard_Spheere from the source code\&.
