.TH "structure_module" 3 "Thu Nov 16 2017" "Version 1" "Hard_Spheere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
structure_module \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBcalc_static_k\fP (difk, knumber)"
.br
.ti -1c
.RI "subroutine \fBcalc_sk_hs_py_mono\fP (vw_option)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine structure_module::calc_sk_hs_py_mono (logical vw_option)"

.PP
Definition at line 22 of file structure_module\&.f90\&.
.SS "subroutine structure_module::calc_static_k (real * 8, intent(in) difk, integer, intent(in) knumber)"

.PP
Definition at line 10 of file structure_module\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hard_Spheere from the source code\&.
