.TH "fortran_Tests/structure_module.f90" 3 "Thu Nov 16 2017" "Version 1" "Hard_Spheere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fortran_Tests/structure_module.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBstructure_module\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBstructure_module::calc_static_k\fP (difk, knumber)"
.br
.ti -1c
.RI "subroutine \fBstructure_module::calc_sk_hs_py_mono\fP (vw_option)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hard_Spheere from the source code\&.
