.TH "Sys_Variables" 3 "Thu Nov 16 2017" "Version 1" "Hard_Spheere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sys_Variables \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <system_variables\&.hpp>\fP
.PP
Inherited by \fBHard_Sphere_Mono\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSys_Variables\fP (int _Ialloc)"
.br
.RI "\fIclase para manejar las variables del sistema\&. \fP"
.ti -1c
.RI "\fBSys_Variables\fP (int _Ialloc, double _vol_fraction)"
.br
.ti -1c
.RI "\fB~Sys_Variables\fP ()"
.br
.ti -1c
.RI "void \fBD0M_ini\fP ()"
.br
.ti -1c
.RI "void \fBrho_ini\fP ()"
.br
.ti -1c
.RI "void \fBprint_rho\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fB_SDimen\fP"
.br
.ti -1c
.RI "int \fB_Species\fP"
.br
.ti -1c
.RI "double * \fB_eta\fP"
.br
.ti -1c
.RI "double * \fB_sigma\fP"
.br
.ti -1c
.RI "double * \fBm_rho\fP"
.br
.ti -1c
.RI "double * \fBm_rho_i\fP"
.br
.ti -1c
.RI "double * \fBd0m\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file system_variables\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Sys_Variables::Sys_Variables (int _Ialloc)\fC [explicit]\fP"

.PP
clase para manejar las variables del sistema\&. 
.PP
\fBAuthor:\fP
.RS 4
Bennigno zempeda & delcranck 
.RE
.PP
\fBDate:\fP
.RS 4
28/08/2017 Inicializacion de todas las variables del sistema\&.
.RE
.PP
Initializes all variables used in this class This is the subroutine Sys_Variables_Alloc in System_Variables_Module file \fBvariables_modules\&.f90\fP 
.PP
Definition at line 8 of file system_variables\&.cpp\&.
.SS "Sys_Variables::Sys_Variables (int _Ialloc, double _vol_fraction)"
Este constructor incluye la fraccion de Volumen\&. 
.PP
Definition at line 23 of file system_variables\&.cpp\&.
.SS "Sys_Variables::~Sys_Variables ()"
Destructor libera la memoria de las variables dinamicas usadas\&. 
.PP
Definition at line 82 of file system_variables\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Sys_Variables::D0M_ini ()"
Initialization of D0M variable Here do not have any argument cause in the fortran program this is : call D0M_ini(species,sigma), and hence we can see that species and sigma are member variable of this class\&.
.PP
Here do not have any argument cause in the fortran program this is : call D0M_ini(species,sigma) and hence we can see that species and sigma are member variable of this class\&. 
.PP
Definition at line 44 of file system_variables\&.cpp\&.
.SS "void Sys_Variables::print_rho ()"

.PP
Definition at line 74 of file system_variables\&.cpp\&.
.SS "void Sys_Variables::rho_ini ()"

.PP
Definition at line 55 of file system_variables\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double* Sys_Variables::_eta\fC [protected]\fP"
Densidad de la dimension de cada especia, en otras palabras la fraciones de volumen 
.PP
Definition at line 49 of file system_variables\&.hpp\&.
.SS "int Sys_Variables::_SDimen\fC [protected]\fP"
Dimension del espacio 
.PP
Definition at line 47 of file system_variables\&.hpp\&.
.SS "double* Sys_Variables::_sigma\fC [protected]\fP"
Dimensioless characteristc distance of each species, Es la dimension de distanciao unidades de distancia, 
.PP
Definition at line 50 of file system_variables\&.hpp\&.
.SS "int Sys_Variables::_Species\fC [protected]\fP"
NUmero de especies usadas en el sistema 
.PP
Definition at line 48 of file system_variables\&.hpp\&.
.SS "double* Sys_Variables::d0m\fC [protected]\fP"

.PP
Definition at line 53 of file system_variables\&.hpp\&.
.SS "double* Sys_Variables::m_rho\fC [protected]\fP"

.PP
Definition at line 51 of file system_variables\&.hpp\&.
.SS "double* Sys_Variables::m_rho_i\fC [protected]\fP"

.PP
Definition at line 52 of file system_variables\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Hard_Spheere from the source code\&.
