.TH "headers/system_variables.hpp" 3 "Thu Nov 16 2017" "Version 1" "Hard_Spheere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers/system_variables.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <iomanip>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSys_Variables\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const double \fBpi\fP = 4\&.0 * atan(1\&.0)"
.br
.ti -1c
.RI "const double \fBdistu\fP = 1\&.e0"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const double distu = 1\&.e0"

.PP
Definition at line 9 of file system_variables\&.hpp\&.
.SS "const double pi = 4\&.0 * atan(1\&.0)"

.PP
Definition at line 8 of file system_variables\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hard_Spheere from the source code\&.
