.TH "system_variables" 3 "Thu Nov 16 2017" "Version 1" "Hard_Spheere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
system_variables \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBsys_variables_alloc\fP (Ialloc)"
.br
.ti -1c
.RI "subroutine \fBd0m_ini\fP (Iallocated_s, species_distance)"
.br
.ti -1c
.RI "subroutine \fBrho_ini\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer \fBsdimen\fP"
.br
.ti -1c
.RI "integer \fBspecies\fP"
.br
.ti -1c
.RI "real *8, dimension(:), allocatable \fBeta\fP"
.br
.ti -1c
.RI "real *8, dimension(:), allocatable \fBsigma\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:), allocatable \fBd0m\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:), allocatable \fBm_rho\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:), allocatable \fBm_rhoi\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine system_variables::d0m_ini (integer, intent(in) Iallocated_s, real * 8, dimension(:), intent(in) species_distance)"

.PP
Definition at line 40 of file variables_modules\&.f90\&.
.SS "subroutine system_variables::rho_ini ()"

.PP
Definition at line 62 of file variables_modules\&.f90\&.
.SS "subroutine system_variables::sys_variables_alloc (integer, intent(in) Ialloc)"

.PP
Definition at line 28 of file variables_modules\&.f90\&.
.SH "Variable Documentation"
.PP 
.SS "real * 8, dimension (:,:), allocatable system_variables::d0m"

.PP
Definition at line 24 of file variables_modules\&.f90\&.
.SS "real * 8, dimension (:), allocatable system_variables::eta"

.PP
Definition at line 22 of file variables_modules\&.f90\&.
.SS "real * 8, dimension (:,:), allocatable system_variables::m_rho"

.PP
Definition at line 25 of file variables_modules\&.f90\&.
.SS "real * 8, dimension (:,:), allocatable system_variables::m_rhoi"

.PP
Definition at line 25 of file variables_modules\&.f90\&.
.SS "integer system_variables::sdimen"

.PP
Definition at line 20 of file variables_modules\&.f90\&.
.SS "real * 8, dimension (:), allocatable system_variables::sigma"

.PP
Definition at line 23 of file variables_modules\&.f90\&.
.SS "integer system_variables::species"

.PP
Definition at line 21 of file variables_modules\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hard_Spheere from the source code\&.
