.TH "fortran_Tests/variables_modules.f90" 3 "Thu Nov 16 2017" "Version 1" "Hard_Spheere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fortran_Tests/variables_modules.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBparameter_variables\fP"
.br
.ti -1c
.RI "module \fBdimensional_variables\fP"
.br
.ti -1c
.RI "module \fBsystem_variables\fP"
.br
.ti -1c
.RI "module \fBpotential_variables\fP"
.br
.ti -1c
.RI "module \fBstatic_variables\fP"
.br
.ti -1c
.RI "module \fBdynamics_variables\fP"
.br
.ti -1c
.RI "module \fBscgle_variables\fP"
.br
.ti -1c
.RI "module \fBnescgle_variables\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBsystem_variables::sys_variables_alloc\fP (Ialloc)"
.br
.ti -1c
.RI "subroutine \fBsystem_variables::d0m_ini\fP (Iallocated_s, species_distance)"
.br
.ti -1c
.RI "subroutine \fBsystem_variables::rho_ini\fP ()"
.br
.ti -1c
.RI "subroutine \fBpotential_variables::z_yuk_mono\fP (dummy, species_number)"
.br
.ti -1c
.RI "subroutine \fBpotential_variables::lambda_sw_mono\fP (dummy)"
.br
.ti -1c
.RI "subroutine \fBstatic_variables::static_variables_mem_alloc\fP (Ialloc_k, Ialloc_s)"
.br
.ti -1c
.RI "subroutine \fBdynamics_variables::dynamics_variables_mem_allocation\fP (time_points, k_points, species_number)"
.br
.ti -1c
.RI "subroutine \fBdynamics_variables::dynamics_variables_mem_deallocation\fP ()"
.br
.ti -1c
.RI "subroutine \fBscgle_variables::kc_ini\fP (Ialloc, kcalpha)"
.br
.ti -1c
.RI "subroutine \fBscgle_variables::calc_lambdak\fP (Ialloc_s, Ialloc_k)"
.br
.ti -1c
.RI "subroutine \fBnescgle_variables::nescgle_static_variables_mem_alloc\fP (Ialloc_k, Ialloc_s)"
.br
.ti -1c
.RI "subroutine \fBnescgle_variables::nescgle_static_variables_mem_dealloc\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, parameter \fBparameter_variables::pi\fP =4\&.d0*DATAN(1\&.d0)"
.br
.ti -1c
.RI "real *8, parameter \fBdimensional_variables::distu\fP =1\&.d0"
.br
.ti -1c
.RI "real *8, parameter \fBdimensional_variables::d0u\fP =1\&.d0"
.br
.ti -1c
.RI "integer \fBsystem_variables::sdimen\fP"
.br
.ti -1c
.RI "integer \fBsystem_variables::species\fP"
.br
.ti -1c
.RI "real *8, dimension(:), allocatable \fBsystem_variables::eta\fP"
.br
.ti -1c
.RI "real *8, dimension(:), allocatable \fBsystem_variables::sigma\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:), allocatable \fBsystem_variables::d0m\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:), allocatable \fBsystem_variables::m_rho\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:), allocatable \fBsystem_variables::m_rhoi\fP"
.br
.ti -1c
.RI "real *8, dimension(:), allocatable \fBpotential_variables::sw_lambda\fP"
.br
.ti -1c
.RI "real *8, dimension(:), allocatable \fBpotential_variables::z_yuk\fP"
.br
.ti -1c
.RI "integer \fBstatic_variables::kpoints\fP"
.br
.ti -1c
.RI "real *8 \fBstatic_variables::dk\fP"
.br
.ti -1c
.RI "real *8, dimension(:), allocatable \fBstatic_variables::k\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:,:), allocatable \fBstatic_variables::sk\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:,:), allocatable \fBstatic_variables::ski\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:,:), allocatable \fBstatic_variables::ck\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:,:), allocatable \fBstatic_variables::hk\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:,:,:), allocatable \fBdynamics_variables::fc\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:,:,:), allocatable \fBdynamics_variables::fs\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:,:), allocatable \fBdynamics_variables::del_z\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:), allocatable \fBdynamics_variables::diffcoeff\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:), allocatable \fBdynamics_variables::msd\fP"
.br
.ti -1c
.RI "real *8, dimension(:), allocatable \fBdynamics_variables::dl\fP"
.br
.ti -1c
.RI "integer \fBdynamics_variables::short_times\fP"
.br
.ti -1c
.RI "integer \fBdynamics_variables::medium_times\fP"
.br
.ti -1c
.RI "integer \fBdynamics_variables::decimations\fP"
.br
.ti -1c
.RI "real *8, dimension(:), allocatable \fBdynamics_variables::m_tau\fP"
.br
.ti -1c
.RI "real *8 \fBdynamics_variables::dtau\fP"
.br
.ti -1c
.RI "real *8, parameter \fBscgle_variables::gamma_max\fP =1\&.0d10"
.br
.ti -1c
.RI "real *8, dimension(:), allocatable \fBscgle_variables::kc\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:,:), allocatable \fBscgle_variables::lambdak\fP"
.br
.ti -1c
.RI "real *8, parameter \fBnescgle_variables::du\fP =1\&.d\-2"
.br
.ti -1c
.RI "real *8, dimension(:,:,:), allocatable \fBnescgle_variables::sk0\fP"
.br
.ti -1c
.RI "real *8, dimension(:,:,:), allocatable \fBnescgle_variables::skf\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hard_Spheere from the source code\&.
