.TH "fortran_Tests/writting_module.f90" 3 "Thu Nov 16 2017" "Version 1" "Hard_Spheere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fortran_Tests/writting_module.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBwritting\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBwritting::sk_writting\fP (File_name)"
.br
.ti -1c
.RI "subroutine \fBwritting::dynamic_writting_tau_dependant\fP (File_name, ik, it, first_time, last_time)"
.br
.ti -1c
.RI "subroutine \fBwritting::dynamic_writting_tau_dependant_multi_k_tests\fP (File_name_Fc, File_name_Fs, ik, it, first_time, last_time, Fc_unit, Fs_unit)"
.br
.ti -1c
.RI "subroutine \fBwritting::dynamic_writting_delz\fP (File_name, it, first_time, last_time)"
.br
.ti -1c
.RI "subroutine \fBwritting::dynamic_writting_fc\fP (File_name, ik, it, first_time, last_time)"
.br
.ti -1c
.RI "subroutine \fBwritting::dynamic_writting_fs\fP (File_name, ik, it, first_time, last_time)"
.br
.ti -1c
.RI "subroutine \fBwritting::dynamic_writting_diff_msd\fP (File_name, it, first_time, last_time)"
.br
.ti -1c
.RI "subroutine \fBwritting::scgle_run_info_file\fP (File_name, gamma_values, System_kind, i_k_test)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hard_Spheere from the source code\&.
